AWSTemplateFormatVersion: "2010-09-09"
Description: This CloudFormation template creates a new SageMaker UserProfile with a specific IAM role for Data Scientist on an existing SageMaker Studio Domain.

Parameters:
  DataScienceUserProfileName:
    Type: String
    Description: The name of the new UserProfile
    Default: data-science

Resources:
  DataScienceSageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AmazonSageMakerExecutionRole-${DataScienceUserProfileName}-${AWS::Region}"
      Policies:
        - PolicyName: iam-pass-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:iam::'
                      - !Ref 'AWS::AccountId'
                      - ':role/service-role/AmazonSageMakerExecutionRole-'
                      - !Ref DataScienceUserProfileName
                      - '-'
                      - !Ref 'AWS::Region'
                  - !Join
                    - ''
                    - - 'arn:aws:iam::'
                      - !Ref 'AWS::AccountId'
                      - ':role/AmazonSageMakerExecutionRole-'
                      - !Ref DataScienceUserProfileName
                      - '-'
                      - !Ref 'AWS::Region'
                Condition:
                  StringEquals:
                    "iam:PassedToService": "sagemaker.amazonaws.com"
        - PolicyName: s3-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: arn:aws:s3:::*
        - PolicyName: sagemaker-common-job-management
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  Action:
                  - sagemaker:CreateTrainingJob
                  - sagemaker:CreateTransformJob
                  - sagemaker:CreateProcessingJob
                  - sagemaker:CreateAutoMLJob
                  - sagemaker:CreateHyperParameterTuningJob
                  - sagemaker:UpdateTrainingJob
                  - sagemaker:CreatePresignedNotebookInstanceUrl
                  - sagemaker:DescribeNotebookInstance
                  - sagemaker:StartNotebookInstance
                  - sagemaker:StopNotebookInstance
                  - sagemaker:CreateNotebookInstanceLifecycleConfig
                  - sagemaker:DeleteNotebookInstanceLifecycleConfig
                  - sagemaker:CreateModelQualityJobDefinition
                  - sagemaker:ListModelQualityJobDefinitions
                  - sagemaker:UpdateModelQualityJobDefinition
                  - sagemaker:DeleteModelQualityJobDefinition
                  - sagemaker:CreateMonitoringSchedule
                  - sagemaker:DescribeMonitoringSchedule
                  - sagemaker:ListMonitoringSchedules
                  - sagemaker:UpdateMonitoringSchedule
                  - sagemaker:DeleteMonitoringSchedule
                  - sagemaker:CreateProject
                  - sagemaker:DescribeProject
                  - sagemaker:ListProjects
                  - sagemaker:UpdateProject
                  - sagemaker:DeleteProject
                  - sagemaker:CreateModel
                  - sagemaker:DescribeModel
                  - sagemaker:ListModels
                  - sagemaker:UpdateModel
                  - sagemaker:DeleteModel
                  - sagemaker:CreateModelPackage
                  - sagemaker:DescribeModelPackage
                  - sagemaker:ListModelPackages
                  - sagemaker:UpdateModelPackage
                  - sagemaker:DeleteModelPackage
                  - sagemaker:CreateModelPackageGroup
                  - sagemaker:DescribeModelPackageGroup
                  - sagemaker:ListModelPackageGroups
                  - sagemaker:UpdateModelPackageGroup
                  - sagemaker:DeleteModelPackageGroup
                Resource: arn:aws:sagemaker:*:*:*/*
              - Effect: Allow
                Action:
                  - sagemaker:Search
                  - sagemaker:ListTrainingJobs
                  - sagemaker:ListTransformJobs
                  - sagemaker:ListProcessingJobs
                  - sagemaker:ListAutoMLJobs
                  - sagemaker:ListCandidatesForAutoMLJob
                  - sagemaker:ListHyperParameterTuningJobs
                  - sagemaker:ListTrainingJobsForHyperParameterTuningJob
                Resource: "*"
        - PolicyName: sagemaker-experiments-management
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:AddAssociation
                  - sagemaker:CreateAction
                  - sagemaker:CreateArtifact
                  - sagemaker:CreateContext
                  - sagemaker:CreateExperiment
                  - sagemaker:CreateTrial
                  - sagemaker:CreateTrialComponent
                  - sagemaker:UpdateAction
                  - sagemaker:UpdateArtifact
                  - sagemaker:UpdateContext
                  - sagemaker:UpdateExperiment
                  - sagemaker:UpdateTrial
                  - sagemaker:UpdateTrialComponent
                  - sagemaker:AssociateTrialComponent
                  - sagemaker:DisassociateTrialComponent
                  - sagemaker:DeleteAssociation
                  - sagemaker:DeleteAction
                  - sagemaker:DeleteArtifact
                  - sagemaker:DeleteContext
                  - sagemaker:DeleteExperiment
                  - sagemaker:DeleteTrial
                  - sagemaker:DeleteTrialComponent
                Resource: arn:aws:sagemaker:*:*:*/*
        - PolicyName: sagemaker-experiments-visualization
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:DescribeAction
                  - sagemaker:DescribeArtifact
                  - sagemaker:DescribeContext
                  - sagemaker:DescribeExperiment
                  - sagemaker:DescribeTrial
                  - sagemaker:DescribeTrialComponent
                  - sagemaker:DescribeLineageGroup
                Resource: arn:aws:sagemaker:*:*:*/*
              - Effect: Allow
                Action:
                  - sagemaker:ListAssociations
                  - sagemaker:ListActions
                  - sagemaker:ListArtifacts
                  - sagemaker:ListContexts
                  - sagemaker:ListExperiments
                  - sagemaker:ListTrials
                  - sagemaker:ListTrialComponents
                  - sagemaker:ListLineageGroups
                  - sagemaker:GetLineageGroupPolicy
                  - sagemaker:QueryLineage
                  - sagemaker:Search
                  - sagemaker:GetSearchSuggestions
                Resource: "*"
        - PolicyName: sagemaker-model-management
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:CreateModel
                  - sagemaker:CreateModelPackage
                  - sagemaker:CreateModelPackageGroup
                  - sagemaker:DescribeModel
                  - sagemaker:DescribeModelPackage
                  - sagemaker:DescribeModelPackageGroup
                  - sagemaker:BatchDescribeModelPackage
                  - sagemaker:UpdateModelPackage
                  - sagemaker:DeleteModel
                  - sagemaker:DeleteModelPackage
                  - sagemaker:DeleteModelPackageGroup
                Resource: arn:aws:sagemaker:*:*:*/*
              - Effect: Allow
                Action:
                  - sagemaker:ListModels
                  - sagemaker:ListModelPackages
                  - sagemaker:ListModelPackageGroups
                Resource: "*"
        - PolicyName: sagemaker-studio-app-permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:CreateApp
                  - sagemaker:DeleteApp
                Resource: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:app/*"
                Condition:
                  "Null":
                    "sagemaker:OwnerUserProfileArn": "true"
              - Effect: Allow
                Action:
                  - sagemaker:CreatePresignedDomainUrl
                Resource:
                  !Join
                  - ''
                  - - 'arn:aws:sagemaker:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':user-profile/${sagemaker:DomainId}/${sagemaker:UserProfileName}'
              - Effect: Allow
                Action:
                  - sagemaker:ListApps
                  - sagemaker:ListDomains
                  - sagemaker:ListUserProfiles
                  - sagemaker:ListSpaces
                  - sagemaker:DescribeApp
                  - sagemaker:DescribeDomain
                  - sagemaker:DescribeUserProfile
                  - sagemaker:DescribeSpace
                Resource: "*"
              - Effect: Allow
                Action:
                  - sagemaker:AddTags
                Resource: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*/*"
                Condition:
                  "Null":
                    "sagemaker:TaggingAction": "false"
              - Effect: Allow
                Action:
                  - sagemaker:CreateSpace
                  - sagemaker:UpdateSpace
                  - sagemaker:DeleteSpace
                Resource:
                  !Join
                  - ''
                  - - 'arn:aws:sagemaker:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':space/${sagemaker:DomainId}/*'
                Condition:
                  "Null":
                    "sagemaker:OwnerUserProfileArn": "true"
              - Effect: Allow
                Action:
                  - sagemaker:CreateSpace
                  - sagemaker:UpdateSpace
                  - sagemaker:DeleteSpace
                Resource:
                  !Join
                  - ''
                  - - 'arn:aws:sagemaker:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':space/${sagemaker:DomainId}/*'
                Condition:
                  ArnLike:
                    "sagemaker:OwnerUserProfileArn":
                      !Join
                      - ''
                      - - 'arn:aws:sagemaker:'
                        - !Ref 'AWS::Region'
                        - ':'
                        - !Ref 'AWS::AccountId'
                        - ':user-profile/${sagemaker:DomainId}/${sagemaker:UserProfileName}'
                  StringEquals:
                    "sagemaker:SpaceSharingType":
                      - "Private"
                      - "Shared"
              - Effect: Allow
                Action:
                  - sagemaker:CreateApp
                  - sagemaker:DeleteApp
                Resource:
                  !Join
                  - ''
                  - - 'arn:aws:sagemaker:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':app/${sagemaker:DomainId}/*'
                Condition:
                  ArnLike:
                    "sagemaker:OwnerUserProfileArn":
                      !Join
                      - ''
                      - - 'arn:aws:sagemaker:'
                        - !Ref 'AWS::Region'
                        - ':'
                        - !Ref 'AWS::AccountId'
                        - ':user-profile/${sagemaker:DomainId}/${sagemaker:UserProfileName}'
                  StringEquals:
                    "sagemaker:SpaceSharingType":
                      - "Private"
              - Effect: Deny
                Sid: DenySageMakerCanvasCreateApp
                Action:
                  - sagemaker:CreateApp
                Resource:
                  !Join
                  - ''
                  - - 'arn:aws:sagemaker:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':app/${sagemaker:DomainId}/${sagemaker:UserProfileName}/canvas/*'
              - Effect: Allow
                Action:
                  - sagemaker:CreateApp
                  - sagemaker:DeleteApp
                Resource: "arn:aws:sagemaker:*:*:app/${sagemaker:DomainId}/*/*/*"
                Condition:
                  StringEquals:
                    "sagemaker:SpaceSharingType":
                      - "Shared"
        - PolicyName: sagemaker-ecr-permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:DescribeImages
                  - ecr:DescribeRepositories
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetAuthorizationToken
                Resource: "*"
        - PolicyName: allow-aws-service-actions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:PutMetricData
                  - ec2:CreateNetworkInterface
                  - ec2:CreateNetworkInterfacePermission
                  - ec2:CreateVpcEndpoint
                  - ec2:DeleteNetworkInterface
                  - ec2:DeleteNetworkInterfacePermission
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeRouteTables
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeVpcs
                  - logs:CreateLogDelivery
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DeleteLogDelivery
                  - logs:Describe*
                  - logs:GetLogDelivery
                  - logs:GetLogEvents
                  - logs:ListLogDeliveries
                  - logs:PutLogEvents
                  - logs:PutResourcePolicy
                  - logs:UpdateLogDelivery
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              Service:
                - bedrock.amazonaws.com
            Action:
              - sts:AssumeRole

  DataScienceUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId: !ImportValue SageMakerDomainId
      UserProfileName: !Ref DataScienceUserProfileName
      UserSettings:
        ExecutionRole: !GetAtt DataScienceSageMakerExecutionRole.Arn

Outputs:
  DataScienceUserProfileArn:
    Description: "The ARN of the new User Profile"
    Value: !GetAtt DataScienceUserProfile.UserProfileArn
